apiVersion: v1
kind: Namespace
metadata:
  name: ccm-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ccm-test
spec:
  replicas: 2
  selector:
    matchLabels: { app: nginx }
  template:
    metadata:
      labels: { app: nginx }
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: ccm-test
  annotations:
    oci.oraclecloud.com/node-label-selector: "role=ingress"
spec:
  type: LoadBalancer
  selector: { app: nginx }
  ports:
  - port: 80
    targetPort: 80
