name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Tidy (generate go.sum)
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...