name: Trivy Scan
on:
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read     # needed to pull from ghcr.io with GITHUB_TOKEN
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: ghcr.io/ronsevetoci/oke-ingress-operator:v0.1.0
          format: table
          exit-code: '1'         # fail the job on findings
          ignore-unfixed: true   # ignore unfixed CVEs
